name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - name: run helloworld
  
        run: echo "hello-world"
